### add aapeli
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "aapeli",
  "name": "Aapo Koivula",
  "password": "fakepassword1"
}

### add onni
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "onni",
  "name": "Onni Ohjelmoija",
  "password": "fakepassword1"
}
